# Generated by Django 2.2.7 on 2019-11-23 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20191123_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('ctype', multiselectfield.db.fields.MultiSelectField(choices=[('enginering', 'enginering'), ('law', 'law'), ('arts', 'arts')], max_length=19)),
                ('clocation', models.CharField(max_length=150)),
                ('cfounded', models.IntegerField()),
                ('cwebsite', models.CharField(max_length=50)),
                ('cdatetime', models.DateTimeField(default=datetime.datetime(2019, 11, 23, 10, 8, 26, 711199))),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups')),
            ],
        ),
    ]
