# Generated by Django 2.2.7 on 2019-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(choices=[('civil', 'civil'), ('compuer organization', 'compuer organization'), ('data structures', 'data structures'), ('mathematics', 'mathematics'), ('chemistry', 'chemistry'), ('electrical', 'electrical'), ('at&c', 'at&c'), ('networking', 'networking'), ('dotnet', 'dotnet'), ('software engineering', 'software engineering'), ('algorthiums', 'algorthiums'), ('c', 'c'), ('physics', 'physics'), ('mechnical', 'mechnical'), ('electronics', 'electronics'), ('java', 'java'), ('management fot it', 'management fot it'), ('dbms', 'dbms')], max_length=50)),
            ],
        ),
    ]
