# Generated by Django 2.2.7 on 2019-11-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_try_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try',
            name='sub',
        ),
    ]
