# Generated by Django 2.2.7 on 2019-11-16 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191116_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try',
            name='drop',
        ),
        migrations.AddField(
            model_name='try',
            name='num',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
