# Generated by Django 2.2.7 on 2019-11-16 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191116_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try',
            name='num',
        ),
        migrations.AddField(
            model_name='try',
            name='pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to='teachers/pics/'),
            preserve_default=False,
        ),
    ]
