# Generated by Django 2.2.7 on 2019-11-17 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191117_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try',
            name='exp',
        ),
        migrations.AddField(
            model_name='try',
            name='txt',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
