# Generated by Django 2.2.7 on 2019-11-27 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 27, 54, 860953)),
        ),
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 27, 54, 844102)),
        ),
        migrations.AlterField(
            model_name='signups',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
