# Generated by Django 2.2.6 on 2019-11-12 08:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signups',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 8, 52, 50, 892512)),
        ),
    ]
