# Generated by Django 2.2.7 on 2019-11-27 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191127_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 617461)),
        ),
        migrations.AlterField(
            model_name='dashbord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 596356)),
        ),
    ]
