# Generated by Django 2.2.6 on 2019-11-13 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191112_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 14, 59, 18, 318449)),
        ),
    ]
