# Generated by Django 2.2.7 on 2019-11-23 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191113_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 10, 8, 26, 686829)),
        ),
    ]
