# Generated by Django 2.2.7 on 2019-11-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191123_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signups',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 10, 16, 25, 315412)),
        ),
    ]
