# Generated by Django 2.2.6 on 2019-11-13 14:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20191113_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeacher',
            fields=[
                ('addteacherID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('instituteType', models.CharField(choices=[('School', ' School'), ('College', 'College')], max_length=15)),
                ('institute', models.CharField(choices=[('svit', 'svit'), ('bmsit', 'bmsit'), ('presidency', 'presidency'), ('ramaiah', 'ramaiah')], max_length=50)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('civil', 'civil'), ('compuer organization', 'compuer organization'), ('data structures', 'data structures'), ('mathematics', 'mathematics'), ('chemistry', 'chemistry'), ('electrical', 'electrical'), ('at&c', 'at&c'), ('networking', 'networking'), ('dotnet', 'dotnet'), ('software engineering', 'software engineering'), ('algorthiums', 'algorthiums'), ('c', 'c'), ('physics', 'physics'), ('mechnical', 'mechnical'), ('electronics', 'electronics'), ('java', 'java'), ('management fot it', 'management fot it'), ('dbms', 'dbms')], max_length=191)),
                ('age', models.IntegerField(default=23)),
                ('expirence', models.CharField(choices=[('1yr', '1yr'), ('2yr', '2yr'), ('3yr', '3yr'), ('5yr', '5yr'), ('8yr', '8yr'), ('15yr', '15yr'), ('15plus', '15plus')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='photos/teachers/addteachers')),
                ('moto', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups')),
            ],
        ),
    ]
