# Generated by Django 2.2.7 on 2019-11-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('exp', models.CharField(choices=[('Best', 'Best'), ('Good', 'Good'), ('Worst', 'Worst')], max_length=20)),
                ('helpp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Guru', 'Guru'), ('Other profession', 'Other profession')], max_length=20)),
                ('suggestion', models.CharField(max_length=1000)),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 23, 10, 220485))),
            ],
        ),
    ]
