# Generated by Django 2.2.7 on 2019-11-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 41, 21, 849471)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
