# Generated by Django 2.2.7 on 2019-11-27 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20191127_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 628767)),
        ),
    ]
