# Generated by Django 2.2.7 on 2019-11-23 10:09

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('stype', multiselectfield.db.fields.MultiSelectField(choices=[('kindergarten', 'kindergarten'), ('primary', 'primary'), ('highschool', 'highschool'), ('preuniversity', 'preuniversity')], max_length=45)),
                ('slocation', models.CharField(max_length=150)),
                ('sfounded', models.IntegerField()),
                ('swebsite', models.CharField(max_length=50)),
                ('sdatetime', models.DateTimeField(default=datetime.datetime(2019, 11, 23, 10, 8, 26, 710390))),
            ],
        ),
    ]
