# Generated by Django 2.2.7 on 2019-11-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='sdatetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 10, 16, 25, 339272)),
        ),
    ]
