# Generated by Django 2.2.7 on 2019-11-27 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 45, 2, 627993)),
        ),
    ]
