# Generated by Django 2.2.7 on 2019-11-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 10, 16, 25, 337300)),
        ),
    ]
