# Generated by Django 2.2.7 on 2019-11-24 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('Engineering', 'Engineering'), ('Law', 'Law'), ('Arts', 'Arts'), ('Commerce', 'Commmerce')], max_length=29)),
                ('describe', models.CharField(choices=[('Prestigious', 'Prestigious'), ('Decent', 'Decent'), ('Average', 'Average')], max_length=20)),
                ('website', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
                ('founded', models.IntegerField(max_length=4)),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 11, 13, 47, 787135))),
            ],
        ),
        migrations.CreateModel(
            name='AddSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('Kidargarden', 'Kidargarden'), ('Primary', 'Primary'), ('HighSChool', 'HighSChool'), ('PreUniversity', 'PreUniversity')], max_length=44)),
                ('describe', models.CharField(choices=[('Prestigious', 'Prestigious'), ('Decent', 'Decent'), ('Average', 'Average')], max_length=20)),
                ('website', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
                ('founded', models.IntegerField(max_length=4)),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 11, 13, 47, 787702))),
            ],
        ),
        migrations.CreateModel(
            name='AddTeacher',
            fields=[
                ('addteacherID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('instituteType', models.CharField(choices=[('School', ' School'), ('College', 'College')], max_length=15)),
                ('institute', models.CharField(choices=[('svit', 'svit'), ('bmsit', 'bmsit'), ('presidency', 'presidency'), ('ramaiah', 'ramaiah')], max_length=50)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('civil', 'civil'), ('compuer organization', 'compuer organization'), ('data structures', 'data structures'), ('mathematics', 'mathematics'), ('chemistry', 'chemistry'), ('electrical', 'electrical'), ('at&c', 'at&c'), ('networking', 'networking'), ('dotnet', 'dotnet'), ('software engineering', 'software engineering'), ('algorthiums', 'algorthiums'), ('c', 'c'), ('physics', 'physics'), ('mechnical', 'mechnical'), ('electronics', 'electronics'), ('java', 'java'), ('management fot it', 'management fot it'), ('dbms', 'dbms')], max_length=50)),
                ('age', models.IntegerField(default=23)),
                ('expirence', models.CharField(choices=[('1yr', '1yr'), ('2yr', '2yr'), ('3yr', '3yr'), ('5yr', '5yr'), ('8yr', '8yr'), ('15yr', '15yr'), ('15plus', '15plus')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/media')),
                ('moto', models.CharField(max_length=10000)),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 11, 13, 47, 786373))),
                ('userID', models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups')),
            ],
        ),
    ]
