# Generated by Django 2.2.7 on 2019-11-20 19:54

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('Engineering', 'Engineering'), ('Law', 'Law'), ('Arts', 'Arts'), ('Commerce', 'Commmerce')], max_length=29)),
                ('describe', models.CharField(choices=[('Prestigious', 'Prestigious'), ('Decent', 'Decent'), ('Average', 'Average')], max_length=20)),
                ('website', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
                ('founded', models.IntegerField(max_length=4)),
                ('image', models.ImageField(blank=True, upload_to='media/colleges')),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 20, 19, 54, 50, 257860))),
            ],
        ),
        migrations.CreateModel(
            name='AddSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('Kidargarden', 'Kidargarden'), ('Primary', 'Primary'), ('HighSChool', 'HighSChool'), ('PreUniversity', 'PreUniversity')], max_length=44)),
                ('describe', models.CharField(choices=[('Prestigious', 'Prestigious'), ('Decent', 'Decent'), ('Average', 'Average')], max_length=20)),
                ('website', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
                ('founded', models.IntegerField(max_length=4)),
                ('image', models.ImageField(blank=True, upload_to='media/school')),
                ('dateTime', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 20, 19, 54, 50, 258283))),
            ],
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 20, 19, 54, 50, 257257)),
        ),
    ]
