# Generated by Django 2.2.7 on 2019-11-27 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 626297)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 627132)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 27, 17, 45, 2, 625671)),
        ),
    ]
