# Generated by Django 2.2.7 on 2019-11-21 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_auto_20191120_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcollege',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addschool',
            name='image',
        ),
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 21, 13, 29, 18, 220676)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 21, 13, 29, 18, 221012)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 21, 13, 29, 18, 220163)),
        ),
    ]
