# Generated by Django 2.2.7 on 2019-11-23 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191123_1009'),
        ('add', '0003_auto_20191121_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteacher',
            name='userID',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 10, 8, 26, 706924)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 10, 8, 26, 707578)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 10, 8, 26, 706109)),
        ),
    ]
