# Generated by Django 2.2.7 on 2019-11-24 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191124_1308'),
        ('add', '0004_auto_20191124_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcollege',
            name='userID',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups'),
        ),
        migrations.AddField(
            model_name='addschool',
            name='userID',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Signups'),
        ),
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 13, 8, 31, 951242)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 13, 8, 31, 951632)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 24, 13, 8, 31, 950763)),
        ),
    ]
