# Generated by Django 2.2.7 on 2019-11-23 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0007_auto_20191123_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 11, 10, 246316)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 11, 10, 246650)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 11, 10, 245840)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='userID',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
