# Generated by Django 2.2.7 on 2019-11-23 12:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0013_auto_20191123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 52, 43, 525428)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 52, 43, 525758)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 12, 52, 43, 524969)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
