# Generated by Django 2.2.7 on 2019-11-23 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0014_auto_20191123_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addteacher',
            name='userID',
        ),
        migrations.AlterField(
            model_name='addcollege',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 13, 21, 22, 324789)),
        ),
        migrations.AlterField(
            model_name='addschool',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 13, 21, 22, 325121)),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='dateTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 23, 13, 21, 22, 324351)),
        ),
    ]
